const products = [
  {
    id: 1,
    name: "Superhero Action Figures",
    price: 149.99,
    category: "Action Figures",
    image: "Actionfigures/1.jpg",
  },
  {
    id: 2,
    name: " Superhero Action Figure",
    price: 139.99,
    category: "Action Figures",
    image: "Actionfigures/5.jpg",
  },
  {
    id: 3,
    name: "Action Figures",
    price: 29.99,
    category: "Action Figures",
    image: "Actionfigures/3.jpg  ",
  },
  {
    id: 4,
    name: "Action Figures",
    price: 149.99,
    category: "Action Figures",
    image: "Actionfigures/4.jpg  ",
  },
  {
    id: 5,
    name: "Action Figures",
    price: 89.99,
    category: "Action Figures",
    image: "Actionfigures/2.jpg  ",
  },
  {
    id: 6,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/6.jpg  ",
  },
  {
    id: 7,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/7.jpg  ",
  },
  {
    id: 8,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/8.jpg  ",
  },
  {
    id: 9,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/9.jpg  ",
  },
  {
    id: 10,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/10.jpg  ",
  },
  {
    id: 11,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/11.jpg  ",
  },
  {
    id: 12,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/12.jpg  ",
  },
  {
    id: 13,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/13.jpg  ",
  },
  {
    id: 14,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/14.jpg  ",
  },
  {
    id: 15,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/15.jpg  ",
  },
  {
    id: 16,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/16.jpg  ",
  },
  {
    id: 17,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/17.jpg  ",
  },
  {
    id: 18,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/18.jpg  ",
  },
  {
    id: 19,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/19.jpg  ",
  },
  {
    id: 20,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/20.jpg  ",
  },
  {
    id: 21,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/21.jpg  ",
  },
  {
    id: 22,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: " Actionfigures/22.jpg ",
  },
  {
    id: 23,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/23.jpg  ",
  },
  {
    id: 24,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/24.jpg  ",
  },
  {
    id: 25,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: " Actionfigures/25.jpg ",
  },
  {
    id: 26,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: " Actionfigures/26.jpg ",
  },
  {
    id: 27,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/27.jpg  ",
  },
  {
    id: 28,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: " Actionfigures/28.jpg ",
  },
  {
    id: 29,
    name: "Action Figures",
    price: 19.99,
    category: "Action Figures",
    image: "Actionfigures/29.jpg  ",
  },
  {
    id: 30,
    name: "Earbuds",
    price: 49.99,
    category: "Computer Gadgets",
    image: "Earbuds/1.jpg  ",
  },
  {
    id: 31,
    name: "Earbuds",
    price: 89.99,
    category: "Computer Gadgets",
    image: "Earbuds/2.jpg  ",
  },
  {
    id: 32,
    name: " Earbuds",
    price: 29.99,
    category: "AEarbuds",
    image: "Earbuds/3.jpg  ",
  },
  {
    id: 33,
    name: "Earbuds",
    price: 149.99,
    category: "Computer Gadgets",
    image: "Earbuds/4.jpg  ",
  },
  {
    id: 34,
    name: " Earbuds",
    price: 39.99,
    category: "Computer Gadgets",
    image: "Earbuds/5.jpg  ",
  },
  {
    id: 35,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/6.jpg  ",
  },
  {
    id: 36,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/7.jpg  ",
  },
  {
    id: 37,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/8.jpg  ",
  },
  {
    id: 38,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/9.jpg  ",
  },
  {
    id: 39,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/10.jpg  ",
  },
  {
    id: 40,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/11.jpg  ",
  },
  {
    id: 41,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/12.jpg  ",
  },
  {
    id: 42,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/13.jpg  ",
  },
  {
    id: 43,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/14.jpg  ",
  },
  {
    id: 44,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/15.jpg  ",
  },
  {
    id: 45,
    name: "Earbuds",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Earbuds/16.jpg  ",
  },
  {
    id: 46,
    name: "Noise-Canceling Headphones",
    price: 49.99,
    category: "Computer Gadgets",
    image: "Headphones/1.jpg  ",
  },
  {
    id: 47,
    name: "Noise-Canceling Headphones",
    price: 89.99,
    category: "Computer Gadgets",
    image: "Headphones/2.jpg  ",
  },
  {
    id: 48,
    name: "Noise-Canceling Headphones",
    price: 29.99,
    category: "Computer Gadgets",
    image: " Headphones/3.jpg ",
  },
  {
    id: 49,
    name: "Noise-Canceling Headphones",
    price: 149.99,
    category: "Computer Gadgets",
    image: " Headphones/4.jpg ",
  },
  {
    id: 50,
    name: "Noise-Canceling Headphones",
    price: 39.99,
    category: "Computer Gadgets",
    image: " Headphones/5.jpg ",
  },
  {
    id: 51,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/6.jpg ",
  },
  {
    id: 52,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/7.jpg ",
  },
  {
    id: 53,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/8.jpg ",
  },
  {
    id: 54,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/9.jpg ",
  },
  {
    id: 55,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/10.jpg ",
  },
  {
    id: 56,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Headphones/11.jpg ",
  },
  {
    id: 57,
    name: "Noise-Canceling Headphones",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Headphones/12.jpg  ",
  },

  {
    id: 58,
    name: "Mechanical Keyboard",
    price: 49.99,
    category: "Computer Gadgets",
    image: "Keyboards/1.jpg  ",
  },
  {
    id: 59,
    name: "Mechanical Keyboard",
    price: 89.99,
    category: "Computer Gadgets",
    image: " Keyboards/2.jpg  ",
  },
  {
    id: 60,
    name: "Mechanical Keyboard",
    price: 29.99,
    category: "Computer Gadgets",
    image: " Keyboards/3.jpg  ",
  },
  {
    id: 61,
    name: "Mechanical Keyboard",
    price: 149.99,
    category: "Computer Gadgets",
    image: " Keyboards/4.jpg  ",
  },
  {
    id: 62,
    name: "Mechanical Keyboard",
    price: 39.99,
    category: "Computer Gadgets",
    image: "Keyboards/5.jpg   ",
  },
  {
    id: 63,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Keyboards/6.jpg  ",
  },
  {
    id: 64,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Keyboards/7.jpg  ",
  },
  {
    id: 65,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Keyboards/8.jpg  ",
  },
  {
    id: 66,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Keyboards/9.jpg   ",
  },
  {
    id: 67,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Keyboards/10.jpg  ",
  },
  {
    id: 68,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Keyboards/11.jpg  ",
  },
  {
    id: 69,
    name: "Mechanical Keyboard",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Keyboards/12.jpg   ",
  },

  {
    id: 70,
    name: "SmartPhone",
    price: 49.99,
    category: "Computer Gadgets",
    image: "Mobiles/1.jpg  ",
  },
  {
    id: 71,
    name: "Smartphone",
    price: 89.99,
    category: "Computer Gadgets",
    image: " Mobiles/2.jpg   ",
  },
  {
    id: 72,
    name: "Smartphone",
    price: 29.99,
    category: "Computer Gadgets",
    image: " Mobiles/3.jpg  ",
  },
  {
    id: 73,
    name: "Smartphone",
    price: 149.99,
    category: "Computer Gadgets",
    image: "Mobiles/4.jpg   ",
  },
  {
    id: 74,
    name: "Smartphone",
    price: 39.99,
    category: "Computer Gadgets",
    image: " Mobiles/5.jpg  ",
  },
  {
    id: 75,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/6.jpg  ",
  },
  {
    id: 76,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/7.jpg  ",
  },
  {
    id: 77,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mobiles/8.jpg   ",
  },
  {
    id: 78,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/9.jpg  ",
  },
  {
    id: 79,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mobiles/10.jpg   ",
  },
  {
    id: 80,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mobiles/11.jpg   ",
  },
  {
    id: 81,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/12.jpg  ",
  },
  {
    id: 82,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mobiles/13.jpg   ",
  },
  {
    id: 83,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/14.jpg  ",
  },
  {
    id: 84,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/15.jpg  ",
  },
  {
    id: 85,
    name: "Smartphone",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mobiles/16.jpg  ",
  },

  {
    id: 86,
    name: "Monitor",
    price: 49.99,
    category: "Computer Gadgets",
    image: " Monitors/1.jpg ",
  },
  {
    id: 87,
    name: "Monitor",
    price: 89.99,
    category: "Computer Gadgets",
    image: " Monitors/2.jpg ",
  },
  {
    id: 88,
    name: "Monitor",
    price: 29.99,
    category: "Computer Gadgets",
    image: "Monitors/3.jpg  ",
  },
  {
    id: 89,
    name: "Monitor",
    price: 149.99,
    category: "Computer Gadgets",
    image: " Monitors/4.jpg ",
  },
  {
    id: 90,
    name: "Monitor",
    price: 39.99,
    category: "Computer Gadgets",
    image: "Monitors/5.jpg  ",
  },
  {
    id: 91,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Monitors/6.jpg  ",
  },
  {
    id: 92,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Monitors/7.jpg  ",
  },
  {
    id: 93,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Monitors/8.jpg  ",
  },
  {
    id: 94,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Monitors/9.jpg ",
  },
  {
    id: 95,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: "  Monitors/10.jpg",
  },
  {
    id: 96,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Monitors/11.jpg ",
  },
  {
    id: 97,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Monitors/12.jpg ",
  },
  {
    id: 98,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Monitors/13.jpg ",
  },
  {
    id: 99,
    name: "Monitor",
    price: 200.99,
    category: "Computer Gadgets",
    image: " Monitors/14.jpg ",
  },
  {
    id: 100,
    name: "Monitor",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Monitors/15.jpg  ",
  },

  {
    id: 101,
    name: "Gaming Mouse",
    price: 49.99,
    category: "Computer Gadgets",
    image: " Mouses/1.jpg ",
  },
  {
    id: 102,
    name: "Gaming Mouse",
    price: 89.99,
    category: "Computer Gadgets",
    image: "  ",
    image: "Mouses/2.jpg   ",
  },
  {
    id: 103,
    name: "Gaming Mouse",
    price: 29.99,
    category: "Computer Gadgets",
    image: " Mouses/3.jpg  ",
  },
  {
    id: 104,
    name: "Gaming Mouse",
    price: 149.99,
    category: "Computer Gadgets",
    image: " Mouses/4.jpg  ",
  },
  {
    id: 105,
    name: "Gaming Mouse",
    price: 39.99,
    category: "Computer Gadgets",
    image: " Mouses/5.jpg  ",
  },
  {
    id: 106,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/6.jpg  ",
  },
  {
    id: 107,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/7.jpg  ",
  },
  {
    id: 108,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mouses/8.jpg   ",
  },
  {
    id: 109,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mouses/9.jpg   ",
  },
  {
    id: 110,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mouses/10.jpg   ",
  },
  {
    id: 111,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mouses/11.jpg  ",
  },
  {
    id: 112,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: "Mouses/12.jpg   ",
  },
  {
    id: 113,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/13.jpg  ",
  },
  {
    id: 114,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/14.jpg  ",
  },
  {
    id: 115,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/15.jpg  ",
  },
  {
    id: 116,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/16.jpg  ",
  },
  {
    id: 17,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/17.jpg  ",
  },
  {
    id: 118,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/18.jpg  ",
  },
  {
    id: 119,
    name: "Gaming Mouse",
    price: 19.99,
    category: "Computer Gadgets",
    image: " Mouses/19.jpg  ",
  },

  {
    id: 120,
    name: "Sport Game",
    price: 49.99,
    category: "Game",
    image: "PCGames/1.jpg  ",
  },
  {
    id: 121,
    name: "Action Adventure Game",
    price: 89.99,
    category: "Game",
    image: " PCGames/2.jpg  ",
  },
  {
    id: 122,
    name: "SAction Game",
    price: 29.99,
    category: "Game",
    image: " PCGames/3.jpg  ",
  },
  {
    id: 123,
    name: "Action Adventure Game",
    price: 149.99,
    category: "Game",
    image: " PCGames/4.jpg  ",
  },
  {
    id: 124,
    name: "Action Adventure Game",
    price: 39.99,
    category: "Game",
    image: " PCGames/5.jpg  ",
  },
  {
    id: 125,
    name: "Action Game",
    price: 19.99,
    category: "Game",
    image: " PCGames/6.jpg  ",
  },
  {
    id: 126,
    name: "Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/7.jpg  ",
  },
  {
    id: 127,
    name: "Action Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/8.jpg  ",
  },
  {
    id: 128,
    name: " Action Adventure Game",
    price: 19.99,
    category: "Game",
    image: " PCGames/9.jpg  ",
  },
  {
    id: 129,
    name: "Action Adventure Game",
    price: 19.99,
    category: "Game",
    image: " PCGames/10.jpg  ",
  },
  {
    id: 130,
    name: "Action Adventure Game",
    price: 19.99,
    category: "Game",
    image: "PCGames/11.jpg   ",
  },
  {
    id: 131,
    name: " Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/12.jpg  ",
  },
  {
    id: 132,
    name: " Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/13.jpg  ",
  },
  {
    id: 133,
    name: " Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/14.jpg  ",
  },
  {
    id: 134,
    name: " Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/15.jpg  ",
  },
  {
    id: 135,
    name: " Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/16.jpg  ",
  },
  {
    id: 136,
    name: "Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/17.jpg  ",
  },
  {
    id: 137,
    name: "Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/18.jpg  ",
  },
  {
    id: 138,
    name: "RAction Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/19.jpg  ",
  },
  {
    id: 139,
    name: "Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/20.jpg  ",
  },
  {
    id: 140,
    name: " Adventure Game ",
    price: 19.99,
    category: "Game",
    image: "PCGames/21.jpg   ",
  },
  {
    id: 141,
    name: "Action Adventure Game ",
    price: 19.99,
    category: "Game",
    image: " PCGames/22.jpg  ",
  },
  {
    id: 142,
    name: "Action Adventure Game",
    price: 19.99,
    category: "Game",
    image: " PCGames/23.jpg  ",
  },
  {
    id: 143,
    name: "Action Adventure Game",
    price: 19.99,
    category: "Game",
    image: " PCGames/24.jpg  ",
  },
];

function shuffleArray(arr) {
  for (let i = arr.length - 1; i > 1; i--) {
    const j = Math.floor(Math.random() * (i - 1)) + 2;
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}

shuffleArray(products);
